name: Update Gemfile.lock

on:
  workflow_dispatch:

jobs:
  update-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local frozen false
          bundle install

      - name: Commit updated Gemfile.lock
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Gemfile.lock
          git commit -m "Update Gemfile.lock with plugins" || echo "Nothing to commit"
          git push
